### ISSUE TITLE
Instructions for shell completions only work for bash

### ISSUE THREAD

**Issue by algal** [fastai/fastec2#3]
The project README says the following:

> To add tab completion for your shell (replace bash with the name of your preferred shell, and .bashrc with your shell's config script):
> 
> `$ fe2 -- --completion bash > ~/.fe2-completion`

But all these invocations generate exactly the same file, a file of bash completions:

```
fe2 -- --completion bash > ~/.fe2-completion
fe2 -- --completion fish > ~/.fe2-completion
fe2 -- --completion zsh > ~/.fe2-completion
fe2 -- --completion sh > ~/.fe2-completion
fe2 -- --completion csh > ~/.fe2-completion
```

**Comment by jph00** [comment]
That's odd. According to the Fire docs, it should work for fish. I'll add a note this may be broken upstream.
https://github.com/google/python-fire/blob/master/docs/using-cli.md#completion-flag
