### ISSUE TITLE
fe2 connect base problem: "Permission denied (publickey)."

### ISSUE THREAD

**Issue by clinicalpersona** [fastai/fastec2#4]
The subject says all: upon launching an instance named "base", fe2 connect failed and issued message:

"Permission denied (publickey)."

The problem, I believe, is the following statement:

os.execvp('ssh', ['ssh', f'{user}@{inst.public_ip_address}', *tunnel])

Here, ssh does not specify private key (-i argument). Therefore, it
will use the default private key, which is ~/.ssh/id_rsa.pub. The 
problem starts if you have _created_ a keypair on AWS, as opposed
to _importing_ it. If you have created a keypair using AWS, then the 
private key ~/.ssh/id_rsa is unrelated to the public key on AWS, and 
of course ssh will not connect

If, on the other hand, you have _imported_ your public key ~/.ssh/id_rsa.pub
into AWS, then your private key ~/.ssh/id_rsa and the public key on AWS
form a matching keypair, and ssh connects.

For now, a proposed solution is to update documentation:

"One thing that will make things a bit easier is if you ensure you have a key pair 
on AWS called “default”. If you don’t, go ahead and upload or create one with that 
name now."

It should say that the "default" public key _must_ be uploaded, not created on AWS.

Alternatively, code could be modified to use a private key downloaded from AWS,
instead of the default key created by ssh-keygen (i.e., ~/.ssh/id_rsa).

**Comment by jph00** [comment]
Thanks will do.
